name: ecpunch
description: AI and BI technology.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  # AWESOME ICONS
  font_awesome_flutter: ^8.8.1

  # PROVIDER
  provider: ^4.1.2

  # FIREBASE
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.4+3

  # FACEBOOK
  flutter_facebook_login: ^3.0.0

  # GOOGLE SIGNIN
  google_sign_in: ^4.4.6

  # COUNTRY PICKER
  country_code_picker: ^1.3.14

  # PIN INPUT
  pin_input_text_field: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
